openapi: 3.0.3
info:
    title: Store API
    description: Service for a complete store with users, products, orders, and cart functionality
    version: 0.0.1
servers:
    - url: http://localhost:8000
paths:
    /cart:
        get:
            tags:
                - store
            summary: getCart store
            operationId: store#getCart
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Cart'
                            example:
                                items:
                                    - productID: Sunt aut distinctio.
                                      quantity: 7880664615933403684
                                    - productID: Sunt aut distinctio.
                                      quantity: 7880664615933403684
                                    - productID: Sunt aut distinctio.
                                      quantity: 7880664615933403684
                                totalAmount: 0.6063468272223981
                                userID: Doloribus recusandae quis occaecati.
    /cart/items:
        post:
            tags:
                - store
            summary: addToCart store
            operationId: store#addToCart
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CartItem'
                        example:
                            productID: Aperiam autem earum.
                            quantity: 1137703197238179332
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Cart'
                            example:
                                items:
                                    - productID: Sunt aut distinctio.
                                      quantity: 7880664615933403684
                                    - productID: Sunt aut distinctio.
                                      quantity: 7880664615933403684
                                    - productID: Sunt aut distinctio.
                                      quantity: 7880664615933403684
                                totalAmount: 0.73241831363072
                                userID: Eos libero non soluta.
    /orders:
        post:
            tags:
                - store
            summary: createOrder store
            operationId: store#createOrder
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/NewOrder'
                        example:
                            items:
                                - price: 0.2386606516661408
                                  productID: Eaque earum ducimus et architecto.
                                  quantity: 4622451897586657234
                                - price: 0.2386606516661408
                                  productID: Eaque earum ducimus et architecto.
                                  quantity: 4622451897586657234
                                - price: 0.2386606516661408
                                  productID: Eaque earum ducimus et architecto.
                                  quantity: 4622451897586657234
                                - price: 0.2386606516661408
                                  productID: Eaque earum ducimus et architecto.
                                  quantity: 4622451897586657234
                            userID: Illum quis.
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Order'
                            example:
                                id: Est doloribus ut at.
                                items:
                                    - price: 0.23952076644196968
                                      productID: Voluptatem a molestias ut amet.
                                      quantity: 6256948739091406382
                                    - price: 0.23952076644196968
                                      productID: Voluptatem a molestias ut amet.
                                      quantity: 6256948739091406382
                                    - price: 0.23952076644196968
                                      productID: Voluptatem a molestias ut amet.
                                      quantity: 6256948739091406382
                                status: Ab occaecati pariatur recusandae eum esse dignissimos.
                                totalAmount: 0.7615839668081023
                                userID: Et nihil nesciunt odio quis et in.
    /orders/{id}:
        get:
            tags:
                - store
            summary: getOrder store
            operationId: store#getOrder
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Ullam voluptates dolore.
                  example: Minima ea consequatur consectetur minima.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Order'
                            example:
                                id: Velit quaerat et.
                                items:
                                    - price: 0.23952076644196968
                                      productID: Voluptatem a molestias ut amet.
                                      quantity: 6256948739091406382
                                    - price: 0.23952076644196968
                                      productID: Voluptatem a molestias ut amet.
                                      quantity: 6256948739091406382
                                    - price: 0.23952076644196968
                                      productID: Voluptatem a molestias ut amet.
                                      quantity: 6256948739091406382
                                status: Quidem mollitia odit quos.
                                totalAmount: 0.8248219502505678
                                userID: Quibusdam debitis.
                "404":
                    description: 'not-found: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /products:
        get:
            tags:
                - store
            summary: listProducts store
            operationId: store#listProducts
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Product'
                                example:
                                    - description: Quia nam et optio fugit facilis harum.
                                      id: Est aperiam sit cupiditate assumenda.
                                      inventory: 5014096451462534631
                                      name: Ea porro laborum nobis dolor.
                                      price: 0.9325272961663225
                                    - description: Quia nam et optio fugit facilis harum.
                                      id: Est aperiam sit cupiditate assumenda.
                                      inventory: 5014096451462534631
                                      name: Ea porro laborum nobis dolor.
                                      price: 0.9325272961663225
                            example:
                                - description: Quia nam et optio fugit facilis harum.
                                  id: Est aperiam sit cupiditate assumenda.
                                  inventory: 5014096451462534631
                                  name: Ea porro laborum nobis dolor.
                                  price: 0.9325272961663225
                                - description: Quia nam et optio fugit facilis harum.
                                  id: Est aperiam sit cupiditate assumenda.
                                  inventory: 5014096451462534631
                                  name: Ea porro laborum nobis dolor.
                                  price: 0.9325272961663225
        post:
            tags:
                - store
            summary: createProduct store
            operationId: store#createProduct
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/NewProduct'
                        example:
                            description: Sint nihil.
                            inventory: 7104625439371326197
                            name: Rem ipsum natus qui.
                            price: 0.4769792471245887
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Product'
                            example:
                                description: In aut qui hic voluptas.
                                id: Eos modi molestiae qui voluptas.
                                inventory: 5102629321985022867
                                name: Et esse quis voluptatem.
                                price: 0.9973809626850958
    /products/{id}:
        get:
            tags:
                - store
            summary: getProduct store
            operationId: store#getProduct
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Quo qui vel laborum amet dolor eius.
                  example: Quia suscipit non.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Product'
                            example:
                                description: Adipisci amet cumque dolores.
                                id: Qui dolores aperiam iusto in perferendis neque.
                                inventory: 3909943467524719308
                                name: Sint consequatur voluptatem.
                                price: 0.5385046741971288
                "404":
                    description: 'not-found: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /users:
        get:
            tags:
                - store
            summary: getUserAll store
            operationId: store#getUserAll
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/User'
                                example:
                                    - email: Ratione excepturi doloremque.
                                      firstName: Ut debitis et voluptates.
                                      id: Aspernatur animi et aperiam.
                                      lastName: Nostrum nostrum ea quae sint qui quia.
                                      username: Esse non consectetur.
                                    - email: Ratione excepturi doloremque.
                                      firstName: Ut debitis et voluptates.
                                      id: Aspernatur animi et aperiam.
                                      lastName: Nostrum nostrum ea quae sint qui quia.
                                      username: Esse non consectetur.
                                    - email: Ratione excepturi doloremque.
                                      firstName: Ut debitis et voluptates.
                                      id: Aspernatur animi et aperiam.
                                      lastName: Nostrum nostrum ea quae sint qui quia.
                                      username: Esse non consectetur.
                            example:
                                - email: Ratione excepturi doloremque.
                                  firstName: Ut debitis et voluptates.
                                  id: Aspernatur animi et aperiam.
                                  lastName: Nostrum nostrum ea quae sint qui quia.
                                  username: Esse non consectetur.
                                - email: Ratione excepturi doloremque.
                                  firstName: Ut debitis et voluptates.
                                  id: Aspernatur animi et aperiam.
                                  lastName: Nostrum nostrum ea quae sint qui quia.
                                  username: Esse non consectetur.
                                - email: Ratione excepturi doloremque.
                                  firstName: Ut debitis et voluptates.
                                  id: Aspernatur animi et aperiam.
                                  lastName: Nostrum nostrum ea quae sint qui quia.
                                  username: Esse non consectetur.
                                - email: Ratione excepturi doloremque.
                                  firstName: Ut debitis et voluptates.
                                  id: Aspernatur animi et aperiam.
                                  lastName: Nostrum nostrum ea quae sint qui quia.
                                  username: Esse non consectetur.
        post:
            tags:
                - store
            summary: createUser store
            operationId: store#createUser
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/NewUser'
                        example:
                            email: Repellat quod natus dolorem perferendis ut.
                            firstName: Aut aut deleniti veniam et eum.
                            lastName: Ipsa sit dolores voluptatem porro.
                            username: Illum nisi.
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
                            example:
                                email: Non ea dolor pariatur autem.
                                firstName: Nam a placeat sapiente.
                                id: Tenetur nobis molestiae enim nam consequatur.
                                lastName: Quis omnis facilis sed nulla eius qui.
                                username: Provident ducimus iure at accusantium sit velit.
    /users/{id}:
        get:
            tags:
                - store
            summary: getUser store
            operationId: store#getUser
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Natus beatae soluta id ab.
                  example: In nihil.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
                            example:
                                email: Facilis sint.
                                firstName: Et minus velit sed alias consequatur dolores.
                                id: Est quibusdam necessitatibus impedit.
                                lastName: Quis itaque sed quo saepe.
                                username: Aut doloremque possimus esse temporibus porro.
                "404":
                    description: 'not-found: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        Cart:
            type: object
            properties:
                items:
                    type: array
                    items:
                        $ref: '#/components/schemas/CartItem'
                    description: Items in the cart
                    example:
                        - productID: Error voluptas iusto est.
                          quantity: 2510491878825256400
                        - productID: Error voluptas iusto est.
                          quantity: 2510491878825256400
                        - productID: Error voluptas iusto est.
                          quantity: 2510491878825256400
                        - productID: Error voluptas iusto est.
                          quantity: 2510491878825256400
                totalAmount:
                    type: number
                    description: Total amount of items in the cart
                    example: 0.6018483941969749
                    format: double
                userID:
                    type: string
                    description: ID of the user who owns the cart
                    example: Tenetur officiis aliquid ex unde.
            example:
                items:
                    - productID: Error voluptas iusto est.
                      quantity: 2510491878825256400
                    - productID: Error voluptas iusto est.
                      quantity: 2510491878825256400
                    - productID: Error voluptas iusto est.
                      quantity: 2510491878825256400
                    - productID: Error voluptas iusto est.
                      quantity: 2510491878825256400
                totalAmount: 0.6210479621956299
                userID: Accusantium accusantium.
            required:
                - userID
                - items
                - totalAmount
        CartItem:
            type: object
            properties:
                productID:
                    type: string
                    description: ID of the product
                    example: Rerum veniam est.
                quantity:
                    type: integer
                    description: Quantity of the product
                    example: 5363965052969001123
                    format: int64
            example:
                productID: Suscipit placeat numquam est aut.
                quantity: 7521936835211857966
            required:
                - productID
                - quantity
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: true
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: true
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: true
            example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        NewOrder:
            type: object
            properties:
                items:
                    type: array
                    items:
                        $ref: '#/components/schemas/OrderItem'
                    description: Items in the order
                    example:
                        - price: 0.013352482669533367
                          productID: Molestias est sit.
                          quantity: 8704328918205676847
                        - price: 0.013352482669533367
                          productID: Molestias est sit.
                          quantity: 8704328918205676847
                        - price: 0.013352482669533367
                          productID: Molestias est sit.
                          quantity: 8704328918205676847
                userID:
                    type: string
                    description: ID of the user placing the order
                    example: Similique dolorum fugit.
            example:
                items:
                    - price: 0.013352482669533367
                      productID: Molestias est sit.
                      quantity: 8704328918205676847
                    - price: 0.013352482669533367
                      productID: Molestias est sit.
                      quantity: 8704328918205676847
                    - price: 0.013352482669533367
                      productID: Molestias est sit.
                      quantity: 8704328918205676847
                userID: Sit facilis tempore eligendi beatae et.
            required:
                - userID
                - items
        NewProduct:
            type: object
            properties:
                description:
                    type: string
                    description: Product description
                    example: Culpa nesciunt qui cumque natus.
                inventory:
                    type: integer
                    description: Available inventory
                    example: 814336597152795003
                    format: int64
                name:
                    type: string
                    description: Product name
                    example: Quo molestias necessitatibus natus.
                price:
                    type: number
                    description: Product price
                    example: 0.3162136823857047
                    format: double
            example:
                description: Perspiciatis sit dolorem.
                inventory: 5491949124356088522
                name: Distinctio esse sed aut.
                price: 0.32937112336048535
            required:
                - name
                - price
                - inventory
        NewUser:
            type: object
            properties:
                email:
                    type: string
                    description: User's email address
                    example: Iure et labore omnis.
                firstName:
                    type: string
                    description: User's first name
                    example: Nisi eum adipisci quia enim.
                lastName:
                    type: string
                    description: User's last name
                    example: Dolor praesentium.
                username:
                    type: string
                    description: User's username
                    example: Autem in libero et inventore.
            example:
                email: Placeat ut ut.
                firstName: Voluptatem rerum ipsam numquam.
                lastName: Sed laboriosam.
                username: Delectus non at suscipit et officiis omnis.
            required:
                - username
                - email
        Order:
            type: object
            properties:
                id:
                    type: string
                    description: Unique order ID
                    example: Enim esse autem delectus autem odio.
                items:
                    type: array
                    items:
                        $ref: '#/components/schemas/OrderItem'
                    description: Items in the order
                    example:
                        - price: 0.013352482669533367
                          productID: Molestias est sit.
                          quantity: 8704328918205676847
                        - price: 0.013352482669533367
                          productID: Molestias est sit.
                          quantity: 8704328918205676847
                        - price: 0.013352482669533367
                          productID: Molestias est sit.
                          quantity: 8704328918205676847
                status:
                    type: string
                    description: Order status
                    example: Sit adipisci.
                totalAmount:
                    type: number
                    description: Total amount of the order
                    example: 0.9338749710370866
                    format: double
                userID:
                    type: string
                    description: ID of the user who placed the order
                    example: Voluptas fuga dolor nostrum autem in.
            example:
                id: Quis cum porro.
                items:
                    - price: 0.013352482669533367
                      productID: Molestias est sit.
                      quantity: 8704328918205676847
                    - price: 0.013352482669533367
                      productID: Molestias est sit.
                      quantity: 8704328918205676847
                    - price: 0.013352482669533367
                      productID: Molestias est sit.
                      quantity: 8704328918205676847
                    - price: 0.013352482669533367
                      productID: Molestias est sit.
                      quantity: 8704328918205676847
                status: Libero provident voluptatibus et aliquid.
                totalAmount: 0.7640809045582072
                userID: Eaque qui nisi sunt ut repudiandae.
            required:
                - id
                - userID
                - items
                - totalAmount
                - status
        OrderItem:
            type: object
            properties:
                price:
                    type: number
                    description: Price of the product at the time of order
                    example: 0.12763795781165693
                    format: double
                productID:
                    type: string
                    description: ID of the product
                    example: Reprehenderit quidem et veritatis.
                quantity:
                    type: integer
                    description: Quantity of the product
                    example: 6017063636513709109
                    format: int64
            example:
                price: 0.996498930056848
                productID: Ut voluptatum exercitationem.
                quantity: 7188773696072811534
            required:
                - productID
                - quantity
                - price
        Product:
            type: object
            properties:
                description:
                    type: string
                    description: Product description
                    example: Ab autem.
                id:
                    type: string
                    description: Unique product ID
                    example: Velit recusandae temporibus eos dolorem voluptas.
                inventory:
                    type: integer
                    description: Available inventory
                    example: 397368625326662266
                    format: int64
                name:
                    type: string
                    description: Product name
                    example: Aliquam libero sunt qui.
                price:
                    type: number
                    description: Product price
                    example: 0.9480788812367933
                    format: double
            example:
                description: Sequi fuga et quia dolor facilis non.
                id: Deserunt aut nesciunt.
                inventory: 2309465020765515610
                name: Delectus a id incidunt distinctio ipsam.
                price: 0.9803215960624804
            required:
                - id
                - name
                - price
                - inventory
        User:
            type: object
            properties:
                email:
                    type: string
                    description: User's email address
                    example: Voluptatem rerum temporibus dolor cupiditate id.
                firstName:
                    type: string
                    description: User's first name
                    example: Odio ipsam et quas.
                id:
                    type: string
                    description: Unique user ID
                    example: Et dolorem et.
                lastName:
                    type: string
                    description: User's last name
                    example: Debitis est.
                username:
                    type: string
                    description: User's username
                    example: Porro dolores aperiam reiciendis provident quasi.
            example:
                email: Rem dolorum.
                firstName: Magnam omnis.
                id: Libero dolores eum in magni provident sapiente.
                lastName: Placeat ut est quod molestias dolorem.
                username: Autem iste aut ipsa tempore.
            required:
                - id
                - username
                - email
tags:
    - name: store
      description: Store service
